version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3.8.14-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    networks:
      - my-default
networks:
  my-default:
    external: true